apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  ENVIRONMENT:    {{ .Values.config.environment | quote }}
  APP_PORT:       {{ .Values.config.appPort | quote }}
  POSTGRES_HOST:  {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT:  {{ .Values.config.postgresPort | quote }}
  POSTGRES_DB:    {{ .Values.config.postgresDb | quote }}
  REDIS_HOST:     {{ .Values.config.redisHost | quote }}
  REDIS_PORT:     {{ .Values.config.redisPort | quote }}