apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  POSTGRES_USER:     {{ .Values.secret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc | quote }}
  REDIS_PASSWORD:    {{ .Values.secret.redisPassword | b64enc | quote }}